"""buat tabel keranjang

Revision ID: 20421f5b19df
Revises: 4e738bff2cf1
Create Date: 2023-11-28 19:25:58.693401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20421f5b19df'
down_revision = '4e738bff2cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id_cart', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_cart')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
