"""add foreign key from user to cart

Revision ID: 25df2a187fc2
Revises: 20421f5b19df
Create Date: 2023-11-28 19:26:57.151707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25df2a187fc2'
down_revision = '20421f5b19df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_carts', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_carts'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_carts')

    # ### end Alembic commands ###
