"""buat tabel

Revision ID: 29315022511d
Revises: bca090207bc9
Create Date: 2023-11-29 15:22:41.649328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29315022511d'
down_revision = 'bca090207bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cake', ['id_kue'], ['id_kue'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
