"""re-create all table and add foreign key

Revision ID: 3c4fe1a81698
Revises: f3978f7bb595
Create Date: 2023-11-29 15:14:56.246628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4fe1a81698'
down_revision = 'f3978f7bb595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cake', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'cake', ['id_cake'], ['id_kue'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_cake')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
