"""delete cart and cart details model

Revision ID: 46be649a1773
Revises: e0dbeefaa9ba
Create Date: 2023-11-28 19:50:51.883476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46be649a1773'
down_revision = 'e0dbeefaa9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('cart_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_details',
    sa.Column('id_cart', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_kue', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jumlahKue', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_cart'], ['cart.id_cart'], name='cart_details_ibfk_1'),
    sa.ForeignKeyConstraint(['id_kue'], ['cake.id_kue'], name='cart_details_ibfk_2'),
    sa.PrimaryKeyConstraint('id_cart'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cart',
    sa.Column('id_cart', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('totalHarga', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='cart_ibfk_1'),
    sa.PrimaryKeyConstraint('id_cart'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
