"""tambah tabel kue

Revision ID: 7561ada72a12
Revises: 0508de0ae64f
Create Date: 2023-11-15 12:14:40.884557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7561ada72a12'
down_revision = '0508de0ae64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cake',
    sa.Column('id_kue', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.Text(), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('varian', sa.String(length=30), nullable=False),
    sa.Column('ukuran', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_kue')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cake')
    # ### end Alembic commands ###
