"""update cart_details

Revision ID: 79248d6cca6b
Revises: 0b06dc465b94
Create Date: 2023-11-28 19:39:36.012816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79248d6cca6b'
down_revision = '0b06dc465b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_kue', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jumlahKue', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'cake', ['id_kue'], ['id_kue'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('jumlahKue')
        batch_op.drop_column('id_kue')

    # ### end Alembic commands ###
