"""change the foreign key name on cart model

Revision ID: 7db286a7c790
Revises: 25df2a187fc2
Create Date: 2023-11-28 19:28:51.766373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7db286a7c790'
down_revision = '25df2a187fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('cart_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id'], ['id'])
        batch_op.drop_column('user_carts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_carts', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_ibfk_1', 'users', ['user_carts'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###
