"""add more column

Revision ID: 8339c37a2a46
Revises: cb78c956a20e
Create Date: 2023-10-26 16:51:16.860376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8339c37a2a46'
down_revision = 'cb78c956a20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_depan', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('nama_belakang', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('no_telp', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('no_telp')
        batch_op.drop_column('nama_belakang')
        batch_op.drop_column('nama_depan')

    # ### end Alembic commands ###
