"""buat id_cart tidak unique pada cart_details dan membuat primary key bayangan pada cart_details

Revision ID: b79bb86be246
Revises: dc7ab549ad6c
Create Date: 2023-11-29 13:36:38.385036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b79bb86be246'
down_revision = 'dc7ab549ad6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('id_cart',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.alter_column('id_cart',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
