"""tambah kolom nama pada tabel order

Revision ID: bf73d2431c66
Revises: f55b90fffeb9
Create Date: 2023-12-20 14:38:27.600783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf73d2431c66'
down_revision = 'f55b90fffeb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('nama')
    # ### end Alembic commands ###
