"""update cart_details & cart

Revision ID: e0dbeefaa9ba
Revises: 79248d6cca6b
Create Date: 2023-11-28 19:41:48.277962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0dbeefaa9ba'
down_revision = '79248d6cca6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalHarga', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('totalHarga')

    # ### end Alembic commands ###
