"""buat kolom message pada tabel cart_details

Revision ID: e7ffcb165679
Revises: 13e8517f5941
Create Date: 2023-12-02 23:00:38.006839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ffcb165679'
down_revision = '13e8517f5941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('message')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index('id', ['user_id'], unique=False)

    # ### end Alembic commands ###
