"""create database testing

Revision ID: ee1f09fcc629
Revises: 
Create Date: 2023-12-07 21:28:01.528725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1f09fcc629'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cake',
    sa.Column('id_kue', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.Text(), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('varian', sa.String(length=30), nullable=False),
    sa.Column('ukuran', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_kue')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=220), nullable=False),
    sa.Column('nama_depan', sa.String(length=30), nullable=False),
    sa.Column('nama_belakang', sa.String(length=30), nullable=True),
    sa.Column('no_telp', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=True),
    sa.Column('foto_profile', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cart',
    sa.Column('id_cart', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_cart')
    )
    op.create_table('cart_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cart', sa.Integer(), nullable=False),
    sa.Column('id_kue', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sub_total', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_cart'], ['cart.id_cart'], ),
    sa.ForeignKeyConstraint(['id_kue'], ['cake.id_kue'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_details')
    op.drop_table('cart')
    op.drop_table('users')
    op.drop_table('cake')
    # ### end Alembic commands ###
