"""buat tabel orders

Revision ID: f87cbfeea8d5
Revises: e7ffcb165679
Create Date: 2023-12-18 17:13:07.254459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87cbfeea8d5'
down_revision = 'e7ffcb165679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id_orders', sa.Integer(), nullable=False),
    sa.Column('pickup_date', sa.String(length=20), nullable=False),
    sa.Column('picktup_time', sa.String(length=20), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(length=40), nullable=False),
    sa.Column('payment_methods', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_orders')
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index('id')

    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cake', ['id_kue'], ['id_kue'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index('id', ['user_id'], unique=False)

    op.drop_table('orders')
    # ### end Alembic commands ###
